USE [master]
GO

/****** Object:  Database [333_MakerLab]    Script Date: 5/4/2015 11:51:59 AM ******/
CREATE DATABASE [333_MakerLab]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'333_MakerLabData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.TITAN\MSSQL\DATA\333_MakerLab.mdf' , SIZE = 6144KB , MAXSIZE = 30720KB , FILEGROWTH = 12%)
 LOG ON 
( NAME = N'333_MakerLabLog', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.TITAN\MSSQL\DATA\333_MakerLab.Idf' , SIZE = 3072KB , MAXSIZE = 22528KB , FILEGROWTH = 17%)
GO

ALTER DATABASE [333_MakerLab] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [333_MakerLab].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [333_MakerLab] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [333_MakerLab] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [333_MakerLab] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [333_MakerLab] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [333_MakerLab] SET ARITHABORT OFF 
GO

ALTER DATABASE [333_MakerLab] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [333_MakerLab] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [333_MakerLab] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [333_MakerLab] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [333_MakerLab] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [333_MakerLab] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [333_MakerLab] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [333_MakerLab] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [333_MakerLab] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [333_MakerLab] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [333_MakerLab] SET  ENABLE_BROKER 
GO

ALTER DATABASE [333_MakerLab] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [333_MakerLab] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [333_MakerLab] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [333_MakerLab] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [333_MakerLab] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [333_MakerLab] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [333_MakerLab] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [333_MakerLab] SET RECOVERY FULL 
GO

ALTER DATABASE [333_MakerLab] SET  MULTI_USER 
GO

ALTER DATABASE [333_MakerLab] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [333_MakerLab] SET DB_CHAINING OFF 
GO

ALTER DATABASE [333_MakerLab] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [333_MakerLab] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [333_MakerLab] SET  READ_WRITE 
GO

